---
deployment:
  tasks:
    - export DEPLOYPATH=/home/corpmember/direct.cilscmglobal/
    - /bin/cp -R application $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R json $DEPLOYPATH
    - /bin/cp -R maitemplate $DEPLOYPATH
    - /bin/cp -R system $DEPLOYPATH
    - /bin/cp -R upload $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
